### ISSUE TITLE
WrappedPathfinders not being removed from EntityAI

### ISSUE THREAD

**Issue by PillBoxUnderScore** [datatags/MobChipLite#2]
### Bug Type

Other Unexpected Behavior

### MobChip Version

1.10.5

### Server Version

1.21 Paper - Latest Dev Build

### Description

Hello again! I'm actually running into two issues funny enough...

The first, in 1.20 I was able to add my custom Pathfinder to Enderman, however I now get an error (specifically when dealing with Enderman):
```
[03:39:55 ERROR]: Could not pass event InventoryClickEvent to ServerCore v1.0
java.lang.MatchException: null
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.abstraction.v1_21_R1.ChipUtil1_21_R1.fromNMS(ChipUtil1_21_R1.java:1191) ~[ServerCore-1.0-Transfer.jar:?]
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.abstraction.v1_21_R1.ChipUtil1_21_R1$3.getFlags(ChipUtil1_21_R1.java:1353) ~[ServerCore-1.0-Transfer.jar:?]
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.abstraction.v1_21_R1.ChipUtil1_21_R1.custom(ChipUtil1_21_R1.java:1335) ~[ServerCore-1.0-Transfer.jar:?]
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.abstraction.v1_21_R1.ChipUtil1_21_R1.toNMS(ChipUtil1_21_R1.java:515) ~[ServerCore-1.0-Transfer.jar:?]
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.abstraction.v1_21_R1.ChipUtil1_21_R1.addPathfinder(ChipUtil1_21_R1.java:527) ~[ServerCore-1.0-Transfer.jar:?]
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.abstraction.ChipUtil.addPathfinders(ChipUtil.java:58) ~[ServerCore-1.0-Transfer.jar:?]
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.bukkit.BukkitAI.updateAI(BukkitAI.java:43) ~[ServerCore-1.0-Transfer.jar:?]
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.bukkit.BukkitAI.add(BukkitAI.java:118) ~[ServerCore-1.0-Transfer.jar:?]
        at ServerCore-1.0-Transfer.jar/me.gamercoder215.mobchip.bukkit.BukkitAI.put(BukkitAI.java:75) ~[ServerCore-1.0-Transfer.jar:?]
```

This is my custom pathfinder
```java
public class FollowOwnerGoal extends CustomPathfinder {
	private UUID owner;
	
	public FollowOwnerGoal(Mob mob, UUID owner) {
		super(mob);
		this.owner = owner;
	}
	
	
	@Override
	public boolean canStart() {
		return farAwayFromOwner(entity, owner);
	}
	
	@Override
	public PathfinderFlag[] getFlags() {
		return new PathfinderFlag[] {PathfinderFlag.JUMPING, PathfinderFlag.MOVEMENT};
	}
	
	@Override
	public void start() {

		goToOwner(BukkitBrain.getBrain(entity), owner);
	}
	
	@Override
	public void tick() {}
	
	public static void goToOwner(EntityBrain brain, UUID owner) {
		Player p = Bukkit.getPlayer(owner);
		brain.getController().moveTo(p, 3f);
		
		brain.getController().lookAt(p);
	}
	
	public boolean farAwayFromOwner(Mob mob, UUID p) {
		if(mob.getLocation().distanceSquared(ownerLocation(p)) > 6) {
			return true;
		} else {
			return false;
		}
	}
	
	private Location ownerLocation(UUID pUUID) {
		Player p = Bukkit.getPlayer(pUUID);
		if(p != null) {
			return p.getLocation();
		} else {
			return null;
		}
	}
}
``` 

2. When attempting to remove specific Goals from an Entity's GoalAI, it seems to not actually be removing any of them. (No error with this one)
```java
private void removeGoals(Mob c) {
			EntityBrain brain = BukkitBrain.getBrain(c);
			EntityAI goalAI = brain.getGoalAI();
			String entityName = c.getType().name();
			List<WrappedPathfinder> goalTargets = new ArrayList<WrappedPathfinder>();
			for (WrappedPathfinder wrapped : goalAI) {
				Pathfinder pf = wrapped.getPathfinder();
				plugin.logMessage("{DEBUG} Checking internal name: '" + pf.getInternalName() + "' of " + entityName);
				switch(pf.getInternalName()) {
				case "LandOnOwnersShoulderGoal" :
					goalTargets.add(wrapped);
					break;
				case "FollowOwnerGoal":
					goalTargets.add(wrapped);
					break;
				case "CatTemptGoal":
					goalTargets.add(wrapped);
					break;
				case "FollowMobGoal":
					goalTargets.add(wrapped);
					break;
				case "BreedGoal":
					goalTargets.add(wrapped);
					break;
				case "TemptGoal":
					goalTargets.add(wrapped);
					break;
				default:
					break;
				}
			}
			if(!goalTargets.isEmpty()) {
				plugin.logMessage("{DEBUG} goalTargets List not empty");
				for(WrappedPathfinder wrapped : goalTargets) {
					Pathfinder pf = wrapped.getPathfinder();
					plugin.logMessage("{DEBUG} Removing " + pf.getInternalName() + " from " + entityName);
					goalAI.remove(pf);
				}
			}
		}
``` 
The debug shows that even though they are being "removed" they still persist after re-scanning the entity's brain.

### Expected Behavior

1. Pathfinder be added to the Enderman allowing them to be teleported to a specific player
2. Goals be removed after being added to a list.

### Actual Behavior

1. Upon attempting to add any Pathfinder to the Enderman, this same error is resulted
2. Entities spawn with the undesired goals still, for instance even through "LandOnOwnersShoulderGoal" should be removed for parrots, they still fly to their owner and attempt to land on their shoulder.

**Comment by datatags** [comment]
Didn't see this issue until just now, sorry! I'll take a look at it soon

**Comment by datatags** [comment]
Seems like a big part of the second issue is Paper's remapping, MobChip uses a lot of indirect reflection that it can't know how to remap. I'll have to do some thinking about how to solve that.

**Comment by datatags** [comment]
So I've been considering this, here are my thoughts

[ReflectionRemapper](https://github.com/jpenilla/reflection-remapper): looks fantastic but needs mappings at runtime, which Paper has but Spigot doesn't, and I'd like to keep Spigot compatibility. I don't think redistributing any form of the mappings is allowed. Maybe mappings could be downloaded at runtime, but that requires internet capability which probably shouldn't be assumed.

Switching on just classes directly: works for selecting between pathfinders which is the main issue, but the reflection to access each pathfinder field is still an issue, I think. Maybe Paper remapper fixes that too, I need to check. Either way, it's not very maintainable since the field names may change at random. Maybe using XSeries' ReflectionUtils could help? This is probably the best short term solution though

I think there was another option I forgot? I should have written down my thoughts back when I was thinking about it regularly 🙃

**Comment by PillBoxUnderScore** [comment]
I actually ended up switching back to Spigot for a couple reasons (the remapping business being the biggest contributor) and dove into the NMS of the entities myself instead of using the API. I loved the API for an introduction into entities, and perhaps on the resource page on Spigot you can add a note of some kind bringing up the new incompatibility of Paper.

I appreciate the reply and taking up some brain space :)
